<a href="https://colab.research.google.com/github/varshinichowdary24/Next-word-prediction-using-LSTM/blob/main/next_word_prediction_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv("/content/qoute_dataset.csv")

In [8]:
df

                                                  quote           Author
0     “The world as we have created it is a process ...  Albert Einstein
1     “It is our choices, Harry, that show what we t...     J.K. Rowling
2     “There are only two ways to live your life. On...  Albert Einstein
3     “The person, be it gentleman or lady, who has ...      Jane Austen
4     “Imperfection is beauty, madness is genius and...   Marilyn Monroe
...                                                 ...              ...
3033      The past beats inside me like a second heart.   John Banville,
3034  Damn, Claire. Warn a guy before you do a face-...    Rachel Caine,
3035  Can you be a girl for a few seconds?""I'm alwa...   Veronica Roth,
3036  That's what fiction is for. It's for getting a...      Tim O'Brien
3037  If we have no peace, it is because we have for...    Mother Teresa

[3038 rows x 2 columns]

In [9]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [10]:
df.shape

(3038, 2)

In [11]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [12]:
quotes = quotes.str.lower()

In [13]:
import string
translator = str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
vocab_size = 10000
tokenizer = Tokenizer(num_words = vocab_size)
tokenizer.fit_on_texts(quotes)

In [16]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[0:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [17]:
sequence = tokenizer.texts_to_sequences(quotes)

In [18]:
for i in range(3):
  print(quotes[i])
  print(sequence[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
“it is our choices harry that show what we truly are far more than our abilities”
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [19]:
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [20]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [21]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [22]:
y

[62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461,
 7,
 70,
 871,
 373,
 9,
 433,
 21,
 19,
 465,
 14,
 294,
 52,
 54,
 70,
 3676,
 14,
 53,
 201,
 714,
 3,
 81,
 15,
 36,
 37,
 7,
 29,
 329,
 93,
 7,
 5,
 1157,
 1,
 101,
 7,
 29,
 329,
 126,
 7,
 5,
 3677,
 116,
 12,
 10,
 2462,
 32,
 1043,
 30,
 82,
 13,
 601,
 11,
 5,
 74,
 1338,
 119,
 12,
 2463,
 3678,
 7,
 313,
 753,
 7,
 638,
 4,
 43,
 144,
 3,
 12,
 682,
 1339,
 54,
 682,
 3680,
 13,
 3,
 202,
 5,
 90,
 8,
 434,
 279,
 202,
 5,
 90,
 8,
 3682,
 7,
 144,
 3,
 12,
 1340,
 17,
 21,
 2,
 14,
 54,
 3,
 12,
 175,
 17,
 21,
 2,
 14,
 3683,
 16,
 13,
 1341,
 191,
 51,
 415,
 2464,
 714,
 9,
 363,
 3684,
 180,
 7,
 39,
 5,
 810,
 1342,
 2,
 46,
 50,
 59,
 322,
 10,
 7,
 168,
 43,
 11,
 639,
 3685,
 111,
 104,
 1045,
 7,
 39,
 2,
 50,
 3686,
 36,
 7,
 21,
 2,
 65,
 10,
 47,
 181,
 21,
 96,
 130,
 3,
 754,
 58,
 123,
 43,
 5,
 1939,
 174,
 18,
 1,
 74,
 208,
 7,
 2,
 94,
 3,
 466,
 59,
 96,
 130,
 3,
 754,
 10,
 58,
 516,
 28,
 12,
 15,
 212,
 948,
 517,
 39,
 10,
 811,
 18,
 51,
 158,
 89,
 132,
 89,
 79,
 1,
 234,
 9,
 271,
 22,
 2,
 146,
 126,
 272,
 15,
 161,
 159,
 212,
 49,
 102,
 79,
 8,
 48,
 389,
 158,
 2466,
 65,
 1,
 159,
 212,
 11,
 1,
 62,
 29,
 17,
 1343,
 167,
 948,
 132,
 4,
 79,
 85,
 4,
 812,
 6,
 273,
 3,
 118,
 10,
 117,
 8,
 48,
 482,
 416,
 105,
 23,
 8,
 48,
 14,
 130,
 3,
 390,
 15,
 92,
 18,
 2,
 140,
 133,
 58,
 55,
 20,
 2,
 133,
 58,
 237,
 46,
 113,
 15,
 2467,
 237,
 46,
 113,
 9,
 417,
 30,
 213,
 2,
 252,
 4,
 9,
 418,
 17,
 126,
 51,
 55,
 2,
 683,
 186,
 182,
 266,
 96,
 1046,
 683,
 44,
 126,
 176,
 260,
 343,
 42,
 4,
 69,
 69,
 69,
 127,
 11,
 100,
 55,
 20,
 2,
 49,
 86,
 30,
 28,
 2468,
 45,
 176,
 15,
 304,
 419,
 176,
 15,
 1570,
 58,
 4,
 117,
 1571,
 176,
 813,
 55,
 872,
 5,
 192,
 91,
 4,
 205,
 45,
 105,
 3,
 289,
 3687,
 344,
 5,
 151,
 640,
 8,
 873,
 3,
 314,
 58,
 3,
 70,
 755,
 18,
 51,
 29,
 105,
 3,
 314,
 58,
 3,
 70,
 3688,
 2,
 140,
 949,
 10,
 3,
 5,
 950,
 467,
 261,
 2,
 49,
 224,
 10,
 1940,
 134,
 13,
 12,
 77,
 178,
 77,
 262,
 32,
 77,
 53,
 76,
 175,
 183,
 76,
 134,
 24,
 170,
 18,
 20,
 76,
 225,
 2,
 147,
 21,
 171,
 602,
 574,
 13,
 2469,
 435,
 404,
 4,
 1,
 201,
 8,
 2,
 134,
 46,
 12,
 345,
 267,
 18,
 20,
 76,
 25,
 65,
 2,
 295,
 951,
 2,
 3,
 64,
 1049,
 4,
 952,
 3,
 128,
 187,
 4,
 354,
 391,
 343,
 953,
 77,
 4,
 133,
 77,
 1,
 117,
 2,
 25,
 76,
 134,
 13,
 12,
 293,
 66,
 2,
 87,
 452,
 8,
 1,
 111,
 18,
 76,
 28,
 133,
 2,
 5,
 208,
 8,
 77,
 9,
 76,
 274,
 2,
 25,
 2470,
 92,
 45,
 49,
 290,
 77,
 49,
 155,
 77,
 49,
 1941,
 4,
 49,
 453,
 52,
 54,
 76,
 25,
 133,
 289,
 27,
 76,
 213,
 2,
 193,
 102,
 77,
 50,
 27,
 76,
 213,
 2,
 436,
 4,
 575,
 77,
 27,
 574,
 13,
 3689,
 39,
 874,
 10,
 1572,
 58,
 1,
 814,
 1942,
 603,
 7,
 5,
 604,
 1943,
 11,
 3690,
 134,
 13,
 16,
 330,
 135,
 6,
 2471,
 3,
 79,
 18,
 6,
 64,
 6,
 16,
 1944,
 58,
 135,
 6,
 756,
 3,
 1945,
 815,
 8,
 24,
 7,
 13,
 273,
 43,
 816,
 1,
 815,
 8,
 495,
 7,
 13,
 1946,
 43,
 816,
 1,
 815,
 8,
 605,
 7,
 13,
 2472,
 43,
 816,
 4,
 1,
 815,
 8,
 36,
 7,
 13,
 214,
 43,
 3691,
 7,
 13,
 5,
 875,
 8,
 24,
 18,
 5,
 875,
 8,
 437,
 9,
 213,
 757,
 3692,
 212,
 74,
 114,
 4,
 5,
 2474,
 876,
 56,
 7,
 1,
 1573,
 3693,
 7,
 21,
 323,
 3,
 73,
 232,
 19,
 14,
 354,
 101,
 3694,
 24,
 2,
 104,
 364,
 59,
 32,
 27,
 32,
 68,
 135,
 6,
 24,
 2,
 576,
 104,
 817,
 32,
 877,
 6,
 24,
 2,
 11,
 56,
 78,
 55,
 6,
 31,
 13,
 50,
 148,
 101,
 78,
 8,
 392,
 18,
 56,
 11,
 120,
 40,
 7,
 47,
 6,
 32,
 2,
 45,
 1344,
 9,
 15,
 315,
 244,
 26,
 758,
 7,
 26,
 315,
 45,
 1344,
 9,
 27,
 6,
 228,
 684,
 15,
 222,
 3695,
 87,
 641,
 2,
 14,
 759,
 2,
 239,
 1948,
 1345,
 8,
 3697,
 2,
 716,
 41,
 2,
 16,
 47,
 67,
 3,
 24,
 3698,
 30,
 577,
 954,
 11,
 1574,
 25,
 65,
 2,
 5,
 1575,
 119,
 389,
 64,
 9,
 954,
 11,
 5,
 1949,
 25,
 65,
 2,
 5,
 3699,
 7,
 11,
 1,
 717,
 8,
 1,
 1576,
 4,
 10,
 134,
 12,
 604,
 68,
 67,
 3,
 67,
 3,
 133,
 5,
 346,
 32,
 1577,
 1576,
 5,
 468,
 3701,
 2,
 14,
 2,
 9,
 7,
 1950,
 54,
 161,
 40,
 7,
 47,
 37,
 393,
 30,
 7,
 2476,
 54,
 2477,
 2,
 57,
 15,
 347,
 3,
 12,
 578,
 124,
 48,
 685,
 686,
 20,
 2,
 57,
 48,
 3,
 12,
 52,
 578,
 124,
 48,
 52,
 685,
 3703,
 7,
 374,
 3,
 81,
 104,
 1578,
 44,
 83,
 469,
 2,
 81,
 45,
 2478,
 9,
 2,
 253,
 29,
 167,
 13,
 16,
 420,
 44,
 23,
 11,
 120,
 818,
 2,
 683,
 63,
 3704,
 28,
 94,
 2,
 68,
 5,
 3,
 1579,
 496,
 28,
 94,
 2,
 3706,
 74,
 91,
 66,
 305,
 27,
 10,
 1158,
 2,
 2,
 131,
 47,
 3708,
 52,
 9,
 2,
 124,
 1,
 52,
 61,
 2,
 28,
 50,
 1,
 52,
 9,
 2,
 203,
 1,
 52,
 642,
 237,
 3709,
 483,
 10,
 7,
 955,
 217,
 15,
 304,
 373,
 18,
 172,
 42,
 275,
 125,
 9,
 266,
 9,
 10,
 7,
 13,
 3711,
 174,
 7,
 235,
 7,
 130,
 3,
 290,
 2,
 2,
 51,
 206,
 3,
 113,
 1,
 234,
 331,
 405,
 3712,
 23,
 8,
 73,
 25,
 31,
 151,
 61,
 18,
 19,
 25,
 31,
 296,
 61,
 22,
 151,
 1951,
 1,
 2480,
 165,
 214,
 7,
 18,
 1,
 394,
 151,
 2481,
 2,
 164,
 7,
 24,
 18,
 5,
 139,
 1346,
 147,
 4,
 86,
 182,
 3714,
 124,
 3,
 50,
 88,
 13,
 3715,
 518,
 25,
 50,
 1,
 332,
 7,
 3,
 3717,
 16,
 69,
 1581,
 9,
 1582,
 28,
 12,
 5,
 194,
 8,
 2483,
 7,
 46,
 85,
 606,
 3,
 12,
 ...]

In [23]:
len(X)

85271

In [24]:
len(y)

85271

In [25]:
max_len = max(len(x) for x in X)
max_len

745

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X,maxlen = max_len,padding = 'pre')

In [27]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [28]:
y = np.array(y)

In [29]:
X_padded.shape

(85271, 745)

In [30]:
y.shape

(85271,)

In [31]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [32]:
y_one_hot.shape

(85271, 10000)

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [34]:
embedding_dim = 50
rnn_units = 128

In [35]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim = vocab_size,output_dim = embedding_dim,
              input_length = max_len)
)

rnn_model.add(SimpleRNN(units = rnn_units))
rnn_model.add(Dense(units = vocab_size,activation = 'softmax'))

rnn_model.compile(optimizer = 'adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [36]:
lstm_model = Sequential()

lstm_model.add(
    Embedding(input_dim = vocab_size,output_dim = embedding_dim,
              input_length = max))

lstm_model.add(LSTM(units = rnn_units))
lstm_model.add(Dense(units = vocab_size,activation = 'softmax'))

In [37]:
lstm_model.compile(optimizer = 'adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [38]:
epochs = 10
batch_size = 128

In [39]:
history_rnn = rnn_model.fit(
    X_padded,y_one_hot,
    epochs = epochs,
    batch_size = batch_size,
    validation_split = 0.2
)

Epoch 1/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 49s 81ms/step - accuracy: 0.0432 - loss: 6.7408 - val_accuracy: 0.0586 - val_loss: 6.6359
Epoch 2/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.0693 - loss: 6.2092 - val_accuracy: 0.0778 - val_loss: 6.4537
Epoch 3/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.0955 - loss: 5.8475 - val_accuracy: 0.0923 - val_loss: 6.3434
Epoch 4/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1095 - loss: 5.5632 - val_accuracy: 0.1017 - val_loss: 6.3480
Epoch 5/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1221 - loss: 5.3144 - val_accuracy: 0.1053 - val_loss: 6.4054
Epoch 6/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1332 - loss: 5.0889 - val_accuracy: 0.1058 - val_loss: 6.4727
Epoch 7/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1458 - loss: 4.8778 - val_accuracy: 0.1075 - val_loss: 6.5247
Epoch 8/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 38s 71ms/step - accuracy: 0.1598 - loss: 4.6777 - val_accuracy: 0.1075 - val_loss: 6.6184
Epoch 9/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 38s 70ms/step - accuracy: 0.1785 - loss: 4.4884 - val_accuracy: 0.1042 - val_loss: 6.6608
Epoch 10/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - accuracy: 0.1973 - loss: 4.3067 - val_accuracy: 0.1042 - val_loss: 6.7342

In [40]:
epochs = 100
batch_size = 120
history_lstm = lstm_model.fit(
    X_padded,y_one_hot,
    epochs = epochs,
    batch_size = batch_size,
    validation_split = 0.1
)

Epoch 1/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.0387 - loss: 6.7542 - val_accuracy: 0.0446 - val_loss: 6.6740
Epoch 2/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.0612 - loss: 6.3053 - val_accuracy: 0.0709 - val_loss: 6.5249
Epoch 3/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.0843 - loss: 6.0268 - val_accuracy: 0.0895 - val_loss: 6.4490
Epoch 4/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1004 - loss: 5.8089 - val_accuracy: 0.0974 - val_loss: 6.4255
Epoch 5/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1116 - loss: 5.6184 - val_accuracy: 0.1041 - val_loss: 6.4158
Epoch 6/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1230 - loss: 5.4415 - val_accuracy: 0.1071 - val_loss: 6.4290
Epoch 7/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.1304 - loss: 5.2827 - val_accuracy: 0.1085 - val_loss: 6.4574
Epoch 8/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1383 - loss: 5.1350 - val_accuracy: 0.1127 - val_loss: 6.4916
Epoch 9/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1454 - loss: 4.9953 - val_accuracy: 0.1110 - val_loss: 6.5335
Epoch 10/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1532 - loss: 4.8596 - val_accuracy: 0.1134 - val_loss: 6.5910
Epoch 11/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1598 - loss: 4.7276 - val_accuracy: 0.1153 - val_loss: 6.6395
Epoch 12/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.1677 - loss: 4.5970 - val_accuracy: 0.1146 - val_loss: 6.6938
Epoch 13/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.1764 - loss: 4.4716 - val_accuracy: 0.1159 - val_loss: 6.7728
Epoch 14/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.1877 - loss: 4.3450 - val_accuracy: 0.1144 - val_loss: 6.8487
Epoch 15/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.2005 - loss: 4.2237 - val_accuracy: 0.1140 - val_loss: 6.9179
Epoch 16/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2142 - loss: 4.1054 - val_accuracy: 0.1106 - val_loss: 6.9923
Epoch 17/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2283 - loss: 3.9931 - val_accuracy: 0.1149 - val_loss: 7.0567
Epoch 18/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.2438 - loss: 3.8859 - val_accuracy: 0.1126 - val_loss: 7.1527
Epoch 19/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2575 - loss: 3.7851 - val_accuracy: 0.1088 - val_loss: 7.2258
Epoch 20/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2716 - loss: 3.6913 - val_accuracy: 0.1110 - val_loss: 7.3176
Epoch 21/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2856 - loss: 3.6025 - val_accuracy: 0.1071 - val_loss: 7.3857
Epoch 22/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.2977 - loss: 3.5217 - val_accuracy: 0.1081 - val_loss: 7.4788
Epoch 23/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3081 - loss: 3.4431 - val_accuracy: 0.1054 - val_loss: 7.5370
Epoch 24/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3203 - loss: 3.3698 - val_accuracy: 0.1082 - val_loss: 7.6198
Epoch 25/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.3322 - loss: 3.3002 - val_accuracy: 0.1078 - val_loss: 7.6934
Epoch 26/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 51ms/step - accuracy: 0.3439 - loss: 3.2334 - val_accuracy: 0.1058 - val_loss: 7.7750
Epoch 27/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.3530 - loss: 3.1694 - val_accuracy: 0.1046 - val_loss: 7.8301
Epoch 28/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3635 - loss: 3.1088 - val_accuracy: 0.1054 - val_loss: 7.9070
Epoch 29/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3730 - loss: 3.0496 - val_accuracy: 0.1006 - val_loss: 7.9617
Epoch 30/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3821 - loss: 2.9928 - val_accuracy: 0.1013 - val_loss: 8.0457
Epoch 31/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.3920 - loss: 2.9363 - val_accuracy: 0.1013 - val_loss: 8.1016
Epoch 32/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.4004 - loss: 2.8842 - val_accuracy: 0.0998 - val_loss: 8.1711
Epoch 33/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.4096 - loss: 2.8325 - val_accuracy: 0.1008 - val_loss: 8.2481
Epoch 34/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.4187 - loss: 2.7825 - val_accuracy: 0.0967 - val_loss: 8.3057
Epoch 35/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.4270 - loss: 2.7340 - val_accuracy: 0.0993 - val_loss: 8.3690
Epoch 36/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.4347 - loss: 2.6873 - val_accuracy: 0.0989 - val_loss: 8.4274
Epoch 37/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 51ms/step - accuracy: 0.4437 - loss: 2.6418 - val_accuracy: 0.0990 - val_loss: 8.4783
Epoch 38/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.4525 - loss: 2.5973 - val_accuracy: 0.0976 - val_loss: 8.5476
Epoch 39/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.4593 - loss: 2.5543 - val_accuracy: 0.0970 - val_loss: 8.6112
Epoch 40/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.4665 - loss: 2.5111 - val_accuracy: 0.0985 - val_loss: 8.6719
Epoch 41/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.4761 - loss: 2.4718 - val_accuracy: 0.0947 - val_loss: 8.7379
Epoch 42/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.4823 - loss: 2.4332 - val_accuracy: 0.0943 - val_loss: 8.7838
Epoch 43/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.4896 - loss: 2.3925 - val_accuracy: 0.0944 - val_loss: 8.8590
Epoch 44/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.4967 - loss: 2.3562 - val_accuracy: 0.0949 - val_loss: 8.9095
Epoch 45/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5047 - loss: 2.3192 - val_accuracy: 0.0946 - val_loss: 8.9725
Epoch 46/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.5109 - loss: 2.2828 - val_accuracy: 0.0949 - val_loss: 9.0239
Epoch 47/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5179 - loss: 2.2473 - val_accuracy: 0.0936 - val_loss: 9.0886
Epoch 48/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5246 - loss: 2.2144 - val_accuracy: 0.0906 - val_loss: 9.1511
Epoch 49/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5307 - loss: 2.1795 - val_accuracy: 0.0908 - val_loss: 9.2108
Epoch 50/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5374 - loss: 2.1487 - val_accuracy: 0.0913 - val_loss: 9.2595
Epoch 51/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.5440 - loss: 2.1168 - val_accuracy: 0.0891 - val_loss: 9.3219
Epoch 52/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5497 - loss: 2.0872 - val_accuracy: 0.0898 - val_loss: 9.3918
Epoch 53/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5564 - loss: 2.0568 - val_accuracy: 0.0892 - val_loss: 9.4200
Epoch 54/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.5620 - loss: 2.0270 - val_accuracy: 0.0875 - val_loss: 9.4746
Epoch 55/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 54ms/step - accuracy: 0.5679 - loss: 1.9991 - val_accuracy: 0.0895 - val_loss: 9.5681
Epoch 56/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5724 - loss: 1.9711 - val_accuracy: 0.0874 - val_loss: 9.6244
Epoch 57/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.5766 - loss: 1.9434 - val_accuracy: 0.0894 - val_loss: 9.6454
Epoch 58/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5839 - loss: 1.9168 - val_accuracy: 0.0885 - val_loss: 9.7252
Epoch 59/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.5888 - loss: 1.8904 - val_accuracy: 0.0861 - val_loss: 9.7830
Epoch 60/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.5937 - loss: 1.8656 - val_accuracy: 0.0863 - val_loss: 9.8492
Epoch 61/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.5983 - loss: 1.8421 - val_accuracy: 0.0838 - val_loss: 9.8869
Epoch 62/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.6047 - loss: 1.8150 - val_accuracy: 0.0874 - val_loss: 9.9425
Epoch 63/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6094 - loss: 1.7926 - val_accuracy: 0.0851 - val_loss: 10.0038
Epoch 64/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6138 - loss: 1.7693 - val_accuracy: 0.0835 - val_loss: 10.0500
Epoch 65/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6196 - loss: 1.7456 - val_accuracy: 0.0820 - val_loss: 10.1005
Epoch 66/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6213 - loss: 1.7246 - val_accuracy: 0.0834 - val_loss: 10.1682
Epoch 67/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6271 - loss: 1.7012 - val_accuracy: 0.0841 - val_loss: 10.2239
Epoch 68/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6317 - loss: 1.6806 - val_accuracy: 0.0803 - val_loss: 10.2846
Epoch 69/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6360 - loss: 1.6581 - val_accuracy: 0.0822 - val_loss: 10.3178
Epoch 70/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6413 - loss: 1.6383 - val_accuracy: 0.0835 - val_loss: 10.3616
Epoch 71/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6448 - loss: 1.6195 - val_accuracy: 0.0827 - val_loss: 10.4076
Epoch 72/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6489 - loss: 1.5990 - val_accuracy: 0.0815 - val_loss: 10.4855
Epoch 73/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6524 - loss: 1.5808 - val_accuracy: 0.0820 - val_loss: 10.5191
Epoch 74/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6572 - loss: 1.5609 - val_accuracy: 0.0838 - val_loss: 10.5561
Epoch 75/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6611 - loss: 1.5417 - val_accuracy: 0.0802 - val_loss: 10.6271
Epoch 76/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6649 - loss: 1.5235 - val_accuracy: 0.0810 - val_loss: 10.6709
Epoch 77/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6689 - loss: 1.5062 - val_accuracy: 0.0810 - val_loss: 10.7319
Epoch 78/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6726 - loss: 1.4886 - val_accuracy: 0.0801 - val_loss: 10.7670
Epoch 79/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6760 - loss: 1.4715 - val_accuracy: 0.0827 - val_loss: 10.8109
Epoch 80/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6798 - loss: 1.4535 - val_accuracy: 0.0821 - val_loss: 10.8594
Epoch 81/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 52ms/step - accuracy: 0.6831 - loss: 1.4375 - val_accuracy: 0.0789 - val_loss: 10.9164
Epoch 82/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.6858 - loss: 1.4236 - val_accuracy: 0.0801 - val_loss: 10.9596
Epoch 83/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6893 - loss: 1.4067 - val_accuracy: 0.0821 - val_loss: 11.0201
Epoch 84/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6947 - loss: 1.3879 - val_accuracy: 0.0799 - val_loss: 11.0383
Epoch 85/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6973 - loss: 1.3748 - val_accuracy: 0.0777 - val_loss: 11.1150
Epoch 86/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7002 - loss: 1.3599 - val_accuracy: 0.0783 - val_loss: 11.1602
Epoch 87/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7041 - loss: 1.3443 - val_accuracy: 0.0817 - val_loss: 11.2419
Epoch 88/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7060 - loss: 1.3294 - val_accuracy: 0.0779 - val_loss: 11.2649
Epoch 89/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7097 - loss: 1.3171 - val_accuracy: 0.0796 - val_loss: 11.3004
Epoch 90/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7133 - loss: 1.3010 - val_accuracy: 0.0792 - val_loss: 11.3495
Epoch 91/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7152 - loss: 1.2873 - val_accuracy: 0.0768 - val_loss: 11.3979
Epoch 92/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7188 - loss: 1.2741 - val_accuracy: 0.0762 - val_loss: 11.4473
Epoch 93/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7212 - loss: 1.2607 - val_accuracy: 0.0774 - val_loss: 11.4868
Epoch 94/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7245 - loss: 1.2459 - val_accuracy: 0.0770 - val_loss: 11.5397
Epoch 95/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7265 - loss: 1.2345 - val_accuracy: 0.0770 - val_loss: 11.5803
Epoch 96/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.7312 - loss: 1.2202 - val_accuracy: 0.0750 - val_loss: 11.6338
Epoch 97/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7328 - loss: 1.2090 - val_accuracy: 0.0750 - val_loss: 11.6768
Epoch 98/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.7342 - loss: 1.1977 - val_accuracy: 0.0763 - val_loss: 11.7274
Epoch 99/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 34s 53ms/step - accuracy: 0.7391 - loss: 1.1839 - val_accuracy: 0.0753 - val_loss: 11.7747
Epoch 100/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.7398 - loss: 1.1741 - val_accuracy: 0.0746 - val_loss: 11.8274

In [42]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [43]:
index_to_word ={}
for word,index in word_index.items():
  index_to_word[index] = word

In [44]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [45]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [47]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

its

In [48]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [50]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokenizer,seed,max_len,10)
print(generate_text)

are you a  little insecure i make mistakes is because they are for

In [52]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [53]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)